DROP DATABASE IF EXISTS TRUONGHOC2;
CREATE DATABASE TRUONGHOC2;
USE TRUONGHOC2;

DROP TABLE IF EXISTS TRUONG;
CREATE TABLE `TRUONG` (
    `MATR` smallint(3) NOT NULL,
    `TENTR` varchar(30) NOT NULL,
    `DCHITR` varchar(100) NOT NULL,
    PRIMARY KEY (`MATR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS HS;
CREATE TABLE `HS` (
    `MAHS` int(8) NOT NULL,
    `HO` varchar(20) NOT NULL,
    `TEN` varchar(15) NOT NULL,
    `CCCD` bigint(12) NOT NULL,
    `NTNS` date DEFAULT NULL,
    `DCHI_HS` varchar(70) DEFAULT NULL,
    PRIMARY KEY (`MAHS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS HOC;
CREATE TABLE `HOC` (
    `MATR` smallint(3) NOT NULL,
    `MAHS` int(8) NOT NULL,
    `NAMHOC` year NOT NULL,
    `DIEMTB` decimal(4,2) NOT NULL,
    `XEPLOAI` enum ('Xuất sắc', 'Giỏi', 'Khá', 'Trung bình', 'Yếu'),
    `KQUA` enum ('Hoàn thành', 'Chưa hoàn thành'),
    PRIMARY KEY (`MATR`, `MAHS`, `NAMHOC`),
    KEY `MATR` (`MATR`),
    KEY `MAHS` (`MAHS`),
    CONSTRAINT `fk_MATR` FOREIGN KEY (`MATR`) REFERENCES `TRUONG` (`MATR`),
    CONSTRAINT `fk_MAHS` FOREIGN KEY (`MAHS`) REFERENCES `HS` (`MAHS`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX `IDX_TENTR` ON TRUONG (`TENTR`);
CREATE INDEX `IDX_XEPLOAI` ON HOC (`XEPLOAI`);
CREATE INDEX `IDX_NAMHOC` ON HOC (`NAMHOC`);

-- Drop foreign key constraints
ALTER TABLE HOC DROP FOREIGN KEY fk_MATR;
ALTER TABLE HOC DROP FOREIGN KEY fk_MAHS;

-- Drop indexes
ALTER TABLE TRUONG DROP INDEX IDX_TENTR;
ALTER TABLE HOC DROP INDEX IDX_XEPLOAI;
ALTER TABLE HOC DROP INDEX IDX_NAMHOC;

-- Perform modifications or fixes on the tables

-- Recreate indexes
ALTER TABLE TRUONG ADD INDEX `IDX_TENTR` (`TENTR`);
ALTER TABLE HOC ADD INDEX `IDX_XEPLOAI` (`XEPLOAI`);
ALTER TABLE HOC ADD INDEX `IDX_NAMHOC` (`NAMHOC`);

-- Recreate foreign key constraints
ALTER TABLE HOC ADD CONSTRAINT `fk_MATR` FOREIGN KEY (`MATR`) REFERENCES `TRUONG` (`MATR`);
ALTER TABLE HOC ADD CONSTRAINT `fk_MAHS` FOREIGN KEY (`MAHS`) REFERENCES `HS` (`MAHS`);
