DROP DATABASE IF EXISTS TRUONGHOC1;
CREATE DATABASE TRUONGHOC1;
USE TRUONGHOC1;

DROP TABLE IF EXISTS TRUONG;
CREATE TABLE `TRUONG` (
    `MATR` smallint(3) NOT NULL,
    `TENTR` varchar(30) NOT NULL,
    `DCHITR` varchar(100) NOT NULL,
    PRIMARY KEY (`MATR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS HS;
CREATE TABLE `HS` (
    `MAHS` int(8) NOT NULL,
    `HO` varchar(20) NOT NULL,
    `TEN` varchar(15) NOT NULL,
    `CCCD` bigint(12) NOT NULL,
    `NTNS` date DEFAULT NULL,
    `DCHI_HS` varchar(70) DEFAULT NULL,
    PRIMARY KEY (`MAHS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS HOC;
CREATE TABLE `HOC` (
    `MATR` smallint(3) NOT NULL,
    `MAHS` int(8) NOT NULL,
    `NAMHOC` year NOT NULL,
    `DIEMTB` decimal(4,2) NOT NULL,
    `XEPLOAI` enum ('Xuất sắc', 'Giỏi', 'Khá', 'Trung bình', 'Yếu'),
    `KQUA` enum ('Hoàn thành', 'Chưa hoàn thành'),
    PRIMARY KEY (`MATR`, `MAHS`, `NAMHOC`),
    KEY `MATR` (`MATR`),
    KEY `MAHS` (`MAHS`),
    CONSTRAINT `fk_MATR` FOREIGN KEY (`MATR`) REFERENCES `TRUONG` (`MATR`),
    CONSTRAINT `fk_MAHS` FOREIGN KEY (`MAHS`) REFERENCES `HS` (`MAHS`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX `MATR` ON TRUONG(`MATR`);
CREATE INDEX `MAHS` ON HS(`MAHS`);
CREATE INDEX `BANGDIEM` ON HOC(`MATR`, `MAHS`, `NAMHOC`);

-- Drop foreign key constraints
ALTER TABLE HOC DROP FOREIGN KEY fk_MATR;
ALTER TABLE HOC DROP FOREIGN KEY fk_MAHS;

-- Drop indexes
ALTER TABLE TRUONG DROP INDEX MATR;
ALTER TABLE HS DROP INDEX MAHS;
ALTER TABLE HOC DROP INDEX BANGDIEM;

-- Perform modifications or fixes on the tables

-- Recreate indexes
ALTER TABLE TRUONG ADD INDEX MATR (MATR);
ALTER TABLE HS ADD INDEX MAHS (MAHS);
ALTER TABLE HOC ADD INDEX BANGDIEM (MATR, MAHS, NAMHOC);

-- Recreate foreign key constraints
ALTER TABLE HOC ADD CONSTRAINT fk_MATR FOREIGN KEY (MATR) REFERENCES TRUONG (MATR);
ALTER TABLE HOC ADD CONSTRAINT fk_MAHS FOREIGN KEY (MAHS) REFERENCES HS (MAHS);

